import head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
export default function Home() {
  return (
    <div>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main>

        <h1>ESTAMOS EN HOME</h1>
        <Link href="/pc/kurtzpel">
          <a >
            juegos
          </a>
        </Link>
        </main>
            </div>
  )
}
